
#Jake Lorah
#Coded in: Python 3.4.3
#FinalProject.py

import turtle
from random import randint
turtle.bgcolor("lightblue")
turtle.speed(10)
turtle.penup()

from pygame import mixer
mixer.init()
mixer.music.load('U:/My Music/music.mp3')
mixer.music.play()

turtle.goto(-70,150)
turtle.write("Jake's Turtle Race",font=("Times New Roman",20,"bold"))
turtle.goto(-170,-20)
turtle.write(0)
turtle.forward(40)
turtle.write(1)
turtle.forward(40)
turtle.write(2)
turtle.forward(40)
turtle.write(3)
turtle.forward(40)
turtle.write(4)
turtle.forward(40)
turtle.write(5)
turtle.forward(40)
turtle.write(6)
turtle.forward(40)
turtle.write(7)
turtle.forward(40)
turtle.write(8)
turtle.forward(40)
turtle.write(9)
turtle.forward(40)
turtle.write(10)
turtle.forward(40)
turtle.write(11)
turtle.forward(40)
turtle.write(12)
turtle.forward(40)
turtle.penup()
turtle.goto(-170,-30)

turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)
turtle.penup()
turtle.backward(175)
turtle.left(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(0)
turtle.pendown()
turtle.forward(175)

turtle.penup()
turtle.backward(175)
turtle.penup()
turtle.left(90)
turtle.penup()
turtle.forward(40)

turtle.penup()
turtle.forward(15)
turtle.penup()
turtle.left(90)
turtle.pendown()
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.left(90)
turtle.forward(580)
turtle.left(90)
turtle.forward(260)
turtle.left(90)
turtle.forward(580)
turtle.left(90)
turtle.forward(260)
turtle.left(90)
turtle.forward(80)

user = input("Type Start to begin the race: ")

while user != "":
    if user == "Start" or user == "START" or user == "start" :
        import random
        jake=turtle.Turtle()

        jake.shape('turtle')
        jake.color("blue")
        jake.penup()
        jake.goto(-200,-40)



        joe=turtle.Turtle()
        joe.shape('turtle')
        joe.color("green")
        joe.penup()
        joe.goto(-200,-90)

             
        mamoon=turtle.Turtle()
        mamoon.shape('turtle')
        mamoon.color("red")
        mamoon.penup()
        mamoon.goto(-200,-140)


        waheeb=turtle.Turtle()
        waheeb.shape('turtle')
        waheeb.color("orange")
        waheeb.penup()
        waheeb.goto(-200,-190)


        for i in range(60) :
            jake.pendown()
            jake.speed(1)
            jake.forward(random.randint(0,15))
            joe.pendown()
            joe.speed(1)
            joe.forward(random.randint(0,15))
            mamoon.pendown()
            mamoon.speed(1)
            mamoon.forward(random.randint(0,15))
            waheeb.pendown()
            waheeb.speed(1)
            waheeb.forward(random.randint(0,15))
            
        if jake.xcor() > joe.xcor() and jake.xcor() > mamoon.xcor() and jake.xcor() > waheeb.xcor():
            turtle.penup()
            turtle.goto(-80,-300)
            turtle.write("The winner is: Blue Turtle!",font=("Times New Roman",20,"bold"))            
        elif joe.xcor() > jake.xcor() and joe.xcor() > mamoon.xcor() and joe.xcor() > waheeb.xcor():
            turtle.penup()
            turtle.goto(-80,-300)
            turtle.write("The winner is: Green Turtle!",font=("Times New Roman",20,"bold"))
        elif mamoon.xcor() > joe.xcor() and mamoon.xcor() > jake.xcor() and mamoon.xcor() > waheeb.xcor():
            turtle.penup()
            turtle.goto(-80,-300)
            turtle.write("The winner is: Red Turtle!",font=("Times New Roman",20,"bold"))
        elif waheeb.xcor() > joe.xcor() and waheeb.xcor() > mamoon.xcor() and waheeb.xcor() > jake.xcor():
            turtle.penup()
            turtle.goto(-80,-300)
            turtle.write("The winner is: Orange Turtle!",font=("Times New Roman",20,"bold"))
            
        user = input("Type Start to begin the race: ")
    else:
        print("Error. Please run the program again.")
        user = input("Type Start to begin the race: ")
